### ISSUE TITLE
Feature: TestSeed  needs to be set in TestRun Model

### ISSUE THREAD

**Issue by mbristol580** [guidewire-oss/fern-junit-client#10]
Currently we are not setting the TestSeed in the TestRun model. 

After further discussion we should set this.  We should set this per sendReport depending on how we process multiple xml

- (Ginko-client) is currently setting this to be the timestamp.
- We can for now set this also as timestamp up to nano seconds. 
- This needs to be unique

**Comment by Monforton** [comment]
> Later we will need to add a suffix to this

What is the suffix / what was the reason for adding a suffix?

**Comment by mbristol580** [comment]
> > Later we will need to add a suffix to this
> 
> What is the suffix / what was the reason for adding a suffix?

i have removed that as it is not time yet for adding a suffix and would require a bigger group coordination
