### ISSUE TITLE
Bug: missing test run start/end times

### ISSUE THREAD

**Issue by eolatham** [guidewire-oss/fern-junit-client#4]
The CLI currently does not set TestRun.StartTime or TestRun.EndTime when sending reports to Fern.

In `parseReports`, it should:
* Set TestRun.StartTime to the earliest SuiteRun.StartTime
* Set TestRun.EndTime to the latest SuiteRun.EndTime

**Comment by mbristol580** [comment]
I believe there is also SuiteRun.StartTime and Endtime. I think we are only setting SpecRun
